spring:
  application:
    name: shoppingmall-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  profiles:
      include: secret

server:
  port: 8082 # 인증서버 포트
