spring:
  application:
    name: shoppingmall-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

#  profiles:
#      active: dev

jwt:
  secret: ${JWT_SECRET} #Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1
  expiration_time: 3600
  refresh_expiration_time: 7200
  token_prefix: Bearer
  header_string: Authorization
  login_url: /api/login

server:
  port: 8082
