spring:
    config:
        activate:
            on-profile: dev

    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:

    jpa:
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.show_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

    h2:
        console:
            enabled: true
            path: /h2-console
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka