jwt:
    expiration-time: 900000 # JWT 토큰 15분
    refresh-expired-time: 604800000 # Refresh 토큰 7일
    secret: Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1 # 비밀키
    token_prefix: Bearer # 모든 토큰 앞에 붙일 내용
    header_string: Authorization # 토큰의 헤더 key
