name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      # Create application-secret.yml from GitHub Secrets
      - name: Create application-secret.yml from GitHub Secrets
        run: |
          mkdir -p src/main/resources
          echo "$APPLICATION_SECRET_YML" > src/main/resources/application-secret.yml
        env:
          APPLICATION_SECRET_YML: ${{ secrets.APPLICATION_SECRET_YML }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run SonarQube
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=${{secrets.SONAR_KEY}} -Dsonar.projectName=${{secrets.SONAR_NAME}} -Dsonar.host.url=${{secrets.SONAR_HOST}} -Dsonar.token=${{secrets.SONAR_TOKEN}}


      - name: Delete file in server
        run: sudo rm -rf /home/nhnacademy/auth

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/home/nhnacademy/auth"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/nhnacademy/auth
            sudo docker stop auth || true
            sudo docker rm auth || true
            sudo docker build -t auth-image .
            sudo docker run -d -p 8082:8082 --name auth --net back_network -e "SPRING_PROFILES_ACTIVE=prod" -v /home/nhnacademy/secret/application-secret.yml:/app/application-secret.yml auth-image